### PR TITLE
Rectangle and SQL Table Style: Fix border-radius for rectangles

### PR DESCRIPTION
**Pull request by exapsy**
Fix for #592 .

- 3D Cubes are unaffected
image

## TODO

- [x] Rectangles now have border radius
- [ ] Rewrite tests so they do not fail because of the new change

### CODE REVIEW

**Comment by alixander** [comment]
can you make an issue for the 3d rounded cube? this does look pretty cool to do one day in the future (https://previews.123rf.com/images/nataliadanilina/nataliadanilina1911/nataliadanilina191100022/134590771-set-of-soft-foam-rubber-blocks-3d-model-of-a-cube-with-perspective-and-rounded-corners-trampoline-pa.jpg)

**Comment by alixander** [comment]
hey @exapsy, I'm hoping we can get this into this next release. What's your bandwidth look like here? No pressure, I appreciate this contribution; if you're too busy with other things, let me know and I can take over.

**Comment by exapsy** [comment]
@alixander Ill take this over ASAP.

**Comment by alixander** [comment]
@exapsy sounds good!

**Comment by alixander** [comment]
@exapsy I made another PR and put you as co-author. Sorry for the rushing here to get it into this release.
https://github.com/terrastruct/d2/pull/688

**Pull request closed without merging**
