### PR TITLE
compress + decompress

### PR DESCRIPTION
**Pull request by alixander**
necessary functions for #153 . right now this can be used by integrations. later we can figure out CLI usage

### CODE REVIEW

**Review by nhooyr — COMMENTED** [review]
why do you need flate here? why encode at all? it's just text, you can just put it in a query parameter directly. I'm sure it's less bytes with flate on larger diagrams but for shorter diagrams it will be significantly more, especially with the overhead of base64.

**Comment by alixander** [comment]
> it's just text, you can just put it in a query parameter directly

i don't understand. how do you do this? what happens when u run into a `/` character?

> I'm sure it's less bytes with flate on larger diagrams but for shorter diagrams it will be significantly more

i think practically, it'll be less bytes for the majority of use cases.

**Comment by nhooyr** [comment]
> i think practically, it'll be less bytes for the majority of use cases.

No way. Have you tested this? I very strongly doubt it. Seriously. It makes little sense with the combined overhead.

Try some examples and report back compared to ascii, I'm genuinely curious now lol.

> i don't understand. how do you do this? what happens when u run into a / character?

URL query parameters accept arbitrary bytes. Characters like `/`, ` ` and other disallowed bytes get encoded with percent signs.

See
1. https://pkg.go.dev/net/url#QueryEscape
2. https://pkg.go.dev/net/url#Values
3. https://pkg.go.dev/net/url#Values.Encode

**Comment by alixander** [comment]
resolved offline. "url encoding is extremely verbose. every non representable character becomes 3 bytes"

**Pull request merged**
