### PR TITLE
d2plugin: Sketch plugin

### PR DESCRIPTION
**Pull request by alixander**
Also implements being able to run D2 with multiple plugins, by adding a `Options()` on d2plugin interface that returns the list of operations the plugin supports.

Screen Shot 2022-11-03 at 5 41 47 PM

See https://github.com/terrastruct/d2/pull/45 for more discussion

### CODE REVIEW

**Comment by nhooyr** [comment]
Update the changelog please.

**Comment by nhooyr** [comment]
And manpage.

**Comment by nhooyr** [comment]
And remember this needs to address my review in https://github.com/terrastruct/d2/pull/45#pullrequestreview-1170967901 before it can be merged.

**Comment by nhooyr** [comment]
think we can get this in for [v0.0.14](https://github.com/terrastruct/d2/milestone/1) on monday?

**Comment by alixander** [comment]
unlikely. there's actually quite a lot here, we'll get it for the release after

**Comment by alixander** [comment]
closing in favor of this: https://github.com/terrastruct/d2/pull/492

(we don't use v8go so no need for it to be a plugin anymore)

**Pull request closed without merging**
