### PR TITLE
d2plugin: Dedup plugins array

### LINKED ISSUE #590: d2 v 0.1.4 crashes on start
```
$ d2
panic:  flag redefined: dagre-nodesep

goroutine 8 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc000136100, 0xc000133720)
        /builddir/d2-0.1.4/_build-d2-xbps/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:848 +0x626
github.com/spf13/pflag.(*FlagSet).VarPF(0xc000780000?, {0x19d85f0, 0xc000860188}, {0xc00051c140, 0xd}, {0x0, 0x0}, {0xc00003e340, 0x32})
        /builddir/d2-0.1.4/_build-d2-xbps/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:831 +0x151
github.com/spf13/pflag.(*FlagSet).VarP(...)
        /builddir/d2-0.1.4/_build-d2-xbps/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:837
github.com/spf13/pflag.(*FlagSet).Int64VarP(0x0?, 0x1042fae?, {0xc00051c140?, 0xc000527480?}, {0x0?, 0x1042fae?}, 0x51?, {0xc00003e340?, 0xd?})
        /builddir/d2-0.1.4/_build-d2-xbps/pkg/mod/github.com/spf13/pflag@v1.0.5/int64.go:46 +0x45
github.com/spf13/pflag.(*FlagSet).Int64P(...)
        /builddir/d2-0.1.4/_build-d2-xbps/pkg/mod/github.com/spf13/pflag@v1.0.5/int64.go:71
oss.terrastruct.com/util-go/xmain.(*Opts).Int64(0xc0004e6680, {0x0, 0x0}, {0xc00051c140, 0xd}, {0x0, 0x0}, 0x1026ada, {0xc00003e340, 0x32})
        /builddir/d2-0.1.4/_build-d2-xbps/pkg/mod/oss.terrastruct.com/util-go@v0.0.0-20221226181616-c04ce7d1b79f/xmain/opts.go:138 +0x1a5
oss.terrastruct.com/d2/d2plugin.(*PluginSpecificFlag).AddToOpts(0xc000136100?, 0xffd638?)
        /builddir/d2-0.1.4/d2plugin/plugin.go:46 +0xd1
main.populateLayoutOpts({0x19d9920?, 0xc0000a21e0?}, 0xc000274000)
        /builddir/d2-0.1.4/main.go:309 +0xc9
main.run({0x19d9878?, 0xc0004e66c0?}, 0xc000274000)
        /builddir/d2-0.1.4/main.go:78 +0x4a5
oss.terrastruct.com/util-go/xmain.(*State).Main.func1()
        /builddir/d2-0.1.4/_build-d2-xbps/pkg/mod/oss.terrastruct.com/util-go@v0.0.0-20221226181616-c04ce7d1b79f/xmain/xmain.go:91 +0x71
created by oss.terrastruct.com/util-go/xmain.(*State).Main
        /builddir/d2-0.1.4/_build-d2-xbps/pkg/mod/oss.terrastruct.com/util-go@v0.0.0-20221226181616-c04ce7d1b79f/xmain/xmain.go:89 +0x155
```

### PR DESCRIPTION
**Pull request by nhooyr**
Closes #590

### CODE REVIEW

**Comment by nhooyr** [comment]
@alixander this PR is a few more lines than it had to be in order to cache the list of plugins and avoid rededupping every time we need the list.

**Review by alixander — APPROVED** [review]
> this PR is a few more lines than it had to be in order to cache the list of plugins and avoid rededupping every time we need the list.

it's a list of like 3 items.

anyway, seems fine. wanna just get rid of d2plugin-dagre here too?

**Comment by nhooyr** [comment]
> it's a list of like 3 items.

give the code a read, it would have ended up executing the tala binary for info like 4 times without the caching of both the list and info struct. lol. there's definitely a meaningful reduction in latency from this. external binary executions add up quickly.

Nah, I'm not really certain removing d2plugin-dagre is the move, let's just leave things as they are for now.

**Comment by alixander** [comment]
the caching of the info struct itself avoids the binary execution latency. the caching of the list is what i'm commenting on

**Comment by nhooyr** [comment]
> the caching of the info struct itself avoids the binary execution latency. the caching of the list is what i'm commenting on

The info struct can't be cached without also caching the list. As when you get a new plugin list, you have new a execPlugin without the cached struct. That's what was causing the two tala license messages in my screen on the issue.

**Pull request merged**
