### PR TITLE
switch dagre to Goja

### PR DESCRIPTION
**Pull request by alixander**

### CODE REVIEW

**Comment by alixander** [comment]
shit got weird. will keep investigating

Screen Shot 2022-12-03 at 10 56 23 AM

**Comment by pleshevskiy** [comment]
> shit got weird. will keep investigating
> 
> Screen Shot 2022-12-03 at 10 56 23 AM

But it's compact.) Are you going to keep the dagre or refuse it completely?

**Comment by alixander** [comment]
nah this render definitely isn't right

**Comment by alixander** [comment]
switched to a different version of dagre and it worked. sick.

**Comment by alixander** [comment]
going to merge this first and then try to get elk and mathjax going

**Pull request merged**
